"""Add page_index (Full-Text Index)

Revision ID: 0b5ccfb3fb3e
Revises: 9ee16cbd79cd
Create Date: 2026-08-14 21:42:41.812698
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0b5ccfb3fb3e'
down_revision = '9ee16cbd79cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_index',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_page.page_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['page_version.version_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_index('ix_page_index_tsv', 'page_index', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_page_index_workspace', 'page_index', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_index_workspace', table_name='page_index')
    op.drop_index('ix_page_index_tsv', table_name='page_index', postgresql_using='gin')
    op.drop_table('page_index')
    # ### end Alembic commands ###
