"""Add ingestion_log; raw_source.workspace_id nullable

Revision ID: 352a65d3d4cc
Revises: a8cb0c9b6944
Create Date: 2026-08-14 20:12:30.979688
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '352a65d3d4cc'
down_revision = 'a8cb0c9b6944'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_log',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=True),
    # Hand-adjusted from the autogenerated sa.Enum(...): the pipeline_state type was
    # already created by the initial migration for raw_source, so these columns must
    # reference it rather than re-issue CREATE TYPE, which would fail on upgrade.
    sa.Column('from_state', postgresql.ENUM(name='pipeline_state', create_type=False), nullable=True),
    sa.Column('to_state', postgresql.ENUM(name='pipeline_state', create_type=False), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['raw_source.source_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_ingestion_log_source_id'), 'ingestion_log', ['source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_log_workspace_id'), 'ingestion_log', ['workspace_id'], unique=False)
    op.alter_column('raw_source', 'workspace_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_source', 'workspace_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index(op.f('ix_ingestion_log_workspace_id'), table_name='ingestion_log')
    op.drop_index(op.f('ix_ingestion_log_source_id'), table_name='ingestion_log')
    op.drop_table('ingestion_log')
    # ### end Alembic commands ###
