"""add connector last_run_detail column

Revision ID: 43f5821bad06
Revises: 7c8a26059991
Create Date: 2026-08-19 16:42:11.019425
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '43f5821bad06'
down_revision = '7c8a26059991'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connector', sa.Column('last_run_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connector', 'last_run_detail')
    # ### end Alembic commands ###
