"""access_policy fuse_access

Revision ID: 7ab85057a869
Revises: 43f5821bad06
Create Date: 2026-08-19 21:16:41.913413
"""

from alembic import op
import sqlalchemy as sa


revision = '7ab85057a869'
down_revision = '43f5821bad06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default so existing rows (any grant created before this column existed) get
    # `false` rather than failing the NOT NULL constraint; dropped after backfill so the
    # model's own `default=False` (Python-side, insert-time only) stays the only source of
    # truth for new rows — same pattern as e139b033f7f3 (workspace.dedicated_index).
    op.add_column(
        'access_policy',
        sa.Column('fuse_access', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('access_policy', 'fuse_access', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_policy', 'fuse_access')
    # ### end Alembic commands ###
