"""add connector table

Revision ID: 7c8a26059991
Revises: f8fb063dacdb
Create Date: 2026-08-19 16:18:47.687124
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7c8a26059991'
down_revision = 'f8fb063dacdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_ref', sa.String(length=512), nullable=True),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingestion_policy', sa.String(length=16), nullable=False),
    sa.Column('state', sa.Enum('enabled', 'disabled', 'disabled_auth', name='connector_state'), nullable=False),
    sa.Column('last_sync_cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('connector_id')
    )
    op.create_index(op.f('ix_connector_workspace_id'), 'connector', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_workspace_id'), table_name='connector')
    op.drop_table('connector')
    # ### end Alembic commands ###
    # Not auto-generated: op.drop_table doesn't drop the enum type it created, unlike
    # create_all's own dedup of CREATE TYPE (models.py's PIPELINE_STATE_ENUM comment) —
    # left as-is, a re-upgrade would hit "type already exists".
    sa.Enum(name='connector_state').drop(op.get_bind(), checkfirst=True)
