"""real schema_version storage

Revision ID: 7eb53cee0b95
Revises: 7ab85057a869
Create Date: 2026-08-20 09:56:02.929681
"""

from alembic import op
import sqlalchemy as sa


revision = '7eb53cee0b95'
down_revision = '7ab85057a869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # `workspace.schema_ref` (dropped below) was always a free-text pointer string with no
    # real content behind it (09 §26) — safe to drop outright rather than migrate any
    # existing values, since none of them were ever anything but a placeholder.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_version',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('restored_from_version_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['restored_from_version_id'], ['schema_version.version_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_schema_version_workspace_id'), 'schema_version', ['workspace_id'], unique=False)
    op.add_column('workspace', sa.Column('current_schema_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_workspace_current_schema_version', 'workspace', 'schema_version', ['current_schema_version_id'], ['version_id'], use_alter=True)
    op.drop_column('workspace', 'schema_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('schema_ref', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint('fk_workspace_current_schema_version', 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'current_schema_version_id')
    op.drop_index(op.f('ix_schema_version_workspace_id'), table_name='schema_version')
    op.drop_table('schema_version')
    # ### end Alembic commands ###
