"""Make review_item.workspace_id nullable

Revision ID: 872ba71a5736
Revises: 0b5ccfb3fb3e
Create Date: 2026-08-16 21:54:24.025053
"""

from alembic import op
import sqlalchemy as sa


revision = '872ba71a5736'
down_revision = '0b5ccfb3fb3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_item', 'workspace_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_item', 'workspace_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
