"""Add access_policy for Phase 1 authorization

Revision ID: a8cb0c9b6944
Revises: d6d8b69c6dc2
Create Date: 2026-08-14 06:48:46.444499
"""

from alembic import op
import sqlalchemy as sa


revision = 'a8cb0c9b6944'
down_revision = 'd6d8b69c6dc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_policy',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('principal', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('reader', 'contributor', 'admin', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'principal')
    )
    op.create_foreign_key('fk_wiki_page_current_version', 'wiki_page', 'page_version', ['current_version_id'], ['version_id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_wiki_page_current_version', 'wiki_page', type_='foreignkey')
    op.drop_table('access_policy')
    # ### end Alembic commands ###
