"""Phase 1a core schema

Revision ID: d6d8b69c6dc2
Revises: 
Create Date: 2026-08-14 06:26:36.387039
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd6d8b69c6dc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('schema_ref', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='workspace_status'), nullable=False),
    sa.Column('storage_bindings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('raw_source',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_shape', sa.Enum('narrative', 'structured_data', name='content_shape'), nullable=True),
    sa.Column('submitted_by', sa.String(length=255), nullable=False),
    sa.Column('artifact_identity', sa.String(length=512), nullable=True),
    sa.Column('source_version', sa.String(length=128), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'superseded', 'archived', 'rejected', name='raw_source_status'), nullable=False),
    sa.Column('pipeline_state', sa.Enum('submitted', 'classifying', 'classified', 'duplicate_check', 'pending_review', 'ingesting', 'ingested', 'error', 'rejected', name='pipeline_state'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supersedes'], ['raw_source.source_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_raw_source_content_hash'), 'raw_source', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_source_workspace_id'), 'raw_source', ['workspace_id'], unique=False)
    op.create_table('review_item',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('submission', 'classification', 'duplicate', 'reindex', 'prune', name='review_kind'), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('subject_ref', sa.String(length=512), nullable=False),
    sa.Column('proposed_action', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='review_status'), nullable=False),
    sa.Column('resolved_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_review_item_workspace_id'), 'review_item', ['workspace_id'], unique=False)
    op.create_table('wiki_page',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('page_type', sa.Enum('overview', 'index', 'log', 'concept', 'entity', 'source', 'comparison', name='page_type'), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='page_status'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['page_version.version_id'], name='fk_wiki_page_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.workspace_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_index(op.f('ix_wiki_page_workspace_id'), 'wiki_page', ['workspace_id'], unique=False)
    op.create_table('page_link',
    sa.Column('from_page_id', sa.UUID(), nullable=False),
    sa.Column('to_page_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.Enum('cross_reference', 'cross_workspace', name='link_type'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_page_id'], ['wiki_page.page_id'], ),
    sa.ForeignKeyConstraint(['to_page_id'], ['wiki_page.page_id'], ),
    sa.PrimaryKeyConstraint('from_page_id', 'to_page_id')
    )
    op.create_table('page_version',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('frontmatter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('diff_ref', sa.String(length=1024), nullable=True),
    sa.Column('trigger', sa.Enum('ingest', 'manual_edit', 'rollback', 'lint_fix', 'prune', name='version_trigger'), nullable=False),
    sa.Column('restored_from_version_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_page.page_id'], ),
    sa.ForeignKeyConstraint(['restored_from_version_id'], ['page_version.version_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_page_version_page_id'), 'page_version', ['page_id'], unique=False)
    op.create_table('index_status',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('index_type', sa.Enum('fts', name='index_type'), nullable=False),
    sa.Column('state', sa.Enum('pending', 'indexing', 'indexed', 'stale', 'error', name='index_state'), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_content_version', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['last_content_version'], ['page_version.version_id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_page.page_id'], ),
    sa.PrimaryKeyConstraint('page_id', 'index_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_status')
    op.drop_index(op.f('ix_page_version_page_id'), table_name='page_version')
    op.drop_table('page_version')
    op.drop_table('page_link')
    op.drop_index(op.f('ix_wiki_page_workspace_id'), table_name='wiki_page')
    op.drop_table('wiki_page')
    op.drop_index(op.f('ix_review_item_workspace_id'), table_name='review_item')
    op.drop_table('review_item')
    op.drop_index(op.f('ix_raw_source_workspace_id'), table_name='raw_source')
    op.drop_index(op.f('ix_raw_source_content_hash'), table_name='raw_source')
    op.drop_table('raw_source')
    op.drop_table('workspace')
    # ### end Alembic commands ###
