"""add query_log table

Revision ID: e24d56055855
Revises: e22a1b4c3004
Create Date: 2026-08-17 14:11:31.841118
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e24d56055855'
down_revision = 'e22a1b4c3004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_log',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('principal', sa.String(length=255), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('resolved_workspaces', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index(op.f('ix_query_log_created_at'), 'query_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_log_principal'), 'query_log', ['principal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_log_principal'), table_name='query_log')
    op.drop_index(op.f('ix_query_log_created_at'), table_name='query_log')
    op.drop_table('query_log')
    # ### end Alembic commands ###
